#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis.mapper-locations=classpath:dao/*xml
mybatis.configuration.map-underscore-to-camel-case=true
#指定Mybatis的实体目录
mybatis.type-aliases-package=com.platform.magnesium_alloy_platform.mybatis.entity

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/model_db
spring.datasource.username=root
spring.datasource.password=050618

aliyun.oss.endpoint=oss-cn-hangzhou.aliyuncs.com
aliyun.oss.accessKeyId=LTAI5tPHwKyXHcmt5sTtnVLg
aliyun.oss.accessKeySecret=sW7nlY9dpQ8v13NrTHoceOPzunmGda
aliyun.oss.bucketName=tyut123
